#!/bin/bash

# get count of arguments
length=$(($#-1))
# get all options but the last one
opts=${@:1:$length}

# get the url (must be the last parameter)
url=${!#}
# split host and path
read host path < <(echo $url | awk -F/ '{ st = index($0,"/");print $1 " " substr($0,st+1)}')

# if we have no path, host is equal to path, so remove path
if [ "$host" == "$path" ]; then
    path=""
fi

# split the host into service and namespace
read service namespace < <(echo $host | tr "." " ")

# split the port from the namespace
read namespace port < <(echo $namespace | tr ":" " ")
if [ "x$port" == "x" ]; then
    port=80
fi

echo http://localhost:8001/api/v1/proxy/namespaces/$namespace/services/$service:$port/$path
echo ""