#!/bin/bash

type=${@:$OPTIND:1}
search=${@:2:1}
read namespace object < <(kube-find $type $search)
if [ "${object}x" == "x" ]; then
    # some objects dont have a namespace
    object=$namespace;
    cmd="kubectl describe $type $object"
else
    cmd="kubectl --namespace=$namespace describe $type $object"
fi

$cmd